metadata:
  name: django-blue
spec:
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
        spec:
  containers:
    - name: django-container
      image: your-dockerhub-username/your-django-image:2.0
      ports:
        - containerPort: 8000
